### ISSUE TITLE
out of bounds bug report

### ISSUE THREAD

**Issue by DimonMobile** [fondueInTheCity/kurs2#1]
![screenshot from 2018-08-16 10-24-53](https://user-images.githubusercontent.com/35412039/44194427-a5698380-a13e-11e8-842a-0e3d0796cd2a.png)
Program crashes on 90 line on linux ubuntu(other os didn't tested). Please make some investigations and fix it

**Comment by DimonMobile** [comment]
![screenshot from 2018-08-16 10-28-37](https://user-images.githubusercontent.com/35412039/44194623-36d8f580-a13f-11e8-9917-f9ded2783de1.png)

**Comment by fondueInTheCity** [comment]
sir, maybe you did not take into account the fact that the array starts at 0. Try changing your tests. Thank you for testing.
Sincerely, the author of this rednecks code

**Comment by DimonMobile** [comment]
I don't input anything
